src/index.tsx
src/style/Theme.ts

Issue #3 
설정 사항 없음
- theme에 색상 5가지 추가
- index.tsx에 ThemeProvider 추가

색상 팔레트 및 테마 설정 추가

---

src/components/StarRating.tsx
src/stories/StarRating.stories.jsx
src/style/GlobalStyle.tsx

별점 컴포넌트가 MUI에 있음
이 라이브러리를 활용할 지 모르니 일단 직접 구현
- 별 반 개 단위는 아직 미구현
- 클릭 시 별점과 호버 시 별점 표시 구현
closes #11

Issue11 별점 컴포넌트 구현

---

src/components/Category.tsx
src/components/CategoryItem.tsx
src/stories/Category.stories.jsx

#18 카테고리 컴포넌트 구현
- 카테고리 컴포넌트 추가 + 스토리북 작성

Issue18 카테고리 컴포넌트 구현

---

src/components/StoreListItem.tsx
src/stories/StoreListItem.stories.jsx

#6 가게 리스트 아이템 컴포넌트 구현
+ 스토리북 작성

Issue6 가게 리스트 아이템 컴포넌트 구현

---

src/components/Chip.tsx
src/stories/Chip.stories.jsx

Issue8 Chip 컴포넌트 구현

---

src/components/CategoryItem.tsx
src/components/StoreList.tsx
src/components/StoreListItem.tsx
src/stories/StoreList.stories.jsx

#21 가게 목록 컴포넌트 구현
+ 스토리북 작성
+ 카테고리 아이템 스타일에서 cursor: pointer 제거

Issue21 가게 목록 컴포넌트 구현

---

src/components/SectionHeader.tsx
src/stories/SectionHeader.stories.jsx

Issue22 섹션 헤더 컴포넌트 구현

---

src/components/StoreDetailTitle.tsx
src/stories/StoreDetailTitle.stories.jsx

<a href="https://github.com/The-Fellowship-of-the-matzip/mat.zip-front/issues/5/">#5</a>
가게 상세페이지 title 컴포넌트 구현

Issue5 가게 title 컴포넌트 구현 

---

src/components/StoreDetailTitle.tsx
src/components/StoreReviewItem.tsx
src/stories/StoreDetailTitle.stories.jsx
src/stories/StoreReviewItem.stories.jsx

<a href="https://github.com/The-Fellowship-of-the-matzip/mat.zip-front/issues/27">#27</a>
가게 상세 페이지에 들어갈 리뷰 콘텐츠 구현 
- [  ] star Icon 의 컴포넌트 화 (생각보다 많이 사용됨) 
- [  ] star Icon의 color 상수화 하기 
- [  ] content width 조정? 
- [  ] 컴포넌트 폴더화!! (너무 하고 싶음....)ㅋㅋㅋ

Issue27 리뷰 Item 컴포넌트 구현 

---

src/components/StoreDetailPage.tsx
src/components/StoreDetailTitle.tsx
src/components/StoreReviewItem.tsx
src/stories/StoreDetailPage.stories.jsx
src/stories/StoreDetailTitle.stories.jsx
src/stories/StoreReviewItem.stories.jsx

<a href="https://github.com/The-Fellowship-of-the-matzip/mat.zip-front/issues/29">#29</a>
기존에 만들었던 Title Component와 Review Item Component 합쳐서 StoreDetailPage 구현

Issue29 Store Detail Page 컴포넌트 구현 

---

src/components/CategoryDetailPage.tsx
src/components/Chip.tsx
src/components/StoreList.tsx
src/stories/CategoryDetailPage.stories.jsx

#33 카테고리 상세 페이지 컴포넌트 구현
전반적으로 width에 맞춰서 글씨 크기 등을 조절할 필요가 있을 듯 
스토리북에서 못생기게 나옴

Issue33 카테고리 상세 페이지 컴포넌트 구현

---

src/components/StoreDetailTitle.tsx

<a href="https://github.com/The-Fellowship-of-the-matzip/mat.zip-front/issues/31">#31</a>
Store Review Item 에서의 불필요한 div 삭제 및 width 값 조정

Issue29 Store Detail Page 타이틀 부분 수정 

---

src/components/CategoryDetailPage.tsx
src/stories/CategoryDetailPage.stories.jsx

#39 카테고리 상세 페이지 props에 categoryName 추가

Issue39 카테고리 상세 페이지 props에 categoryName 추가

---

src/components/Star.tsx
src/components/StarRating.tsx
src/components/StoreDetailTitle.tsx
src/components/StoreListItem.tsx
src/components/StoreReviewItem.tsx
src/stories/Star.stories.jsx
src/stories/StarRating.stories.jsx
src/style/Theme.ts

#42 별 컴포넌트 구현
- 스토리북 작성
- 별 컴포넌트 다른 페이지에 적용
일단 당장은 filled냐, outlined냐 정도만 바꿀 수 있게 했습니당
폰트 크기 변경은 나중에

Issue42 별 컴포넌트 구현

---

package-lock.json
package.json
src/components/CategoryDetailPage.tsx
src/components/SearchBar.tsx
src/components/SectionHeader.tsx
src/stories/Searchbar.stories.jsx
src/stories/SectionHeader.stories.jsx

#43 아이콘 react-icons로 변경
- SearchBar의 돋보기 아이콘
- SectionHeader의 leadingButton 아이콘(뒤로가기)

Issue43 아이콘 react-icons로 변경

---

src/components/Header.tsx
src/hooks/useLogin.tsx

<a href="https://github.com/The-Fellowship-of-the-matzip/mat.zip-front/issues/46">#46</a>
로그인 링크 붙이기 
sessionStorage의 여부를 확인하여서 sessionStorage에 accessToken이 있을 경우 userProfile, 없을 경우 로그인 링크를 보여준다

Issue46 로그인 링크 붙이기 

---

src/components/StoreDetailPage.tsx

#49 
가게 세부 페이지 기본 이미지 
태태 스토리북 이미지 연결

Issue49 스토리북 이미지 연결 

---

src/components/CategoryDetailPage.tsx
src/components/CategoryPage.tsx
src/components/InfiniteScroll.tsx
src/mock/data.ts

페이징 기능 미구현
무한 스크롤 기능을 추가, 기본 페이지, 카테고리 디테일 페이지에 가게 로드 시 적용
- 무한 스크롤 적용할 수 있는 컴포넌트 구현

Issue56 무한 스크롤을 통한 페이징 구현

---

src/components/common/BottomSheet/BottomSheet.style.tsx
src/components/common/BottomSheet/BottomSheet.tsx
src/components/layout/Header/Header.style.tsx
src/components/layout/Header/Header.tsx
src/components/layout/MenuDrawer/MenuDrawer.style.tsx
src/components/layout/MenuDrawer/MenuDrawer.tsx
src/components/layout/PageLayout/PageLayout.style.tsx
src/style/GlobalStyle.tsx

Closes #80 
상단바 구성에 로고 + 검색 버튼 + 프로필/로그인 버튼으로 되어있음
요소를 추가적으로 배치할 공간 부족
로고 + 검색 + 햄버거 메뉴로 변경 및 햄버거 메뉴 클릭 시 측면 메뉴 서랍 오픈 구현
메뉴 서랍으로 로그인 및 로그아웃 이동
메뉴 서랍에 캠퍼스 변경 버튼 추가

Issue80 상단바 구조 변경, 햄버거 메뉴 및 우측 메뉴 서랍 구현

---

src/components/common/StarRating/StarRating.tsx
src/components/common/StoreList/StoreList.tsx
src/components/pages/CategoryDetailPage/index.tsx
src/components/pages/CategoryPage/index.tsx
src/components/pages/StoreDetailPage/ReviewInputBottomSheet/ReviewInputBottomSheet.tsx
src/components/pages/StoreDetailPage/StoreDetailTitle/StoreDetailTitle.tsx
src/components/pages/StoreDetailPage/StoreReviewItem/StoreReviewItem.tsx
src/components/pages/StoreDetailPage/index.tsx
src/index.tsx
src/mock/data.ts
src/mock/handlers/restaurantHandler.ts
src/mock/handlers/reviewHandler.ts

Issue82 리액트 쿼리 연결하기 

---

package-lock.json
package.json
src/App.tsx
src/components/common/StoreList/StoreList.tsx
src/components/common/StoreListItem/StoreListItem.tsx
src/components/pages/CategoryDetailPage/index.tsx
src/components/pages/CategoryPage/index.tsx
src/components/pages/StoreDetailPage/StoreDetailTitle/StoreDetailTitle.tsx
src/components/pages/StoreDetailPage/index.tsx
src/index.tsx
src/mock/handlers/reviewHandler.ts

Issue85 실제 서버와 연결 및 임시 배포

---

src/components/pages/StoreDetailPage/StoreDetailTitle/StoreDetailTitle.style.tsx
src/components/pages/StoreDetailPage/StoreDetailTitle/StoreDetailTitle.tsx
src/components/pages/StoreDetailPage/StoreReviewItem/StoreReviewItem.style.tsx
src/components/pages/StoreDetailPage/index.style.tsx
src/components/pages/StoreDetailPage/index.tsx
src/mock/data.ts

프로필 이미지 그림자 추가
상세 페이지 정보 부분 수정, 이미지 크롭 수정

기타 스타일 추가 수정

---

src/App.tsx
src/components/common/SearchBar/SearchBar.style.tsx
src/components/common/SearchBar/SearchBar.tsx
src/components/layout/Header/Header.tsx
src/components/pages/SearchResultPage/SearchResultPage.style.tsx
src/components/pages/SearchResultPage/SearchResultPage.tsx

검색 UI만 있고, 기능이 구현되지 않음
검색어를 입력하면 검색 결과가 나오도록 구현
Closes #97

Issue97 검색 기능 구현

---

src/App.tsx
src/components/common/ErrorImage/ErrorImage.style.tsx
src/components/common/ErrorImage/ErrorImage.tsx
src/components/common/Image/Image.tsx
src/components/common/Spinner/Spinner.style.tsx
src/components/common/Spinner/Spinner.tsx
src/components/common/StoreListItem/StoreListItem.style.tsx
src/components/layout/Header/Header.style.tsx
src/components/layout/Header/Header.tsx
src/components/pages/CategoryDetailPage/CategoryDetailPage.tsx
src/components/pages/CategoryPage/CategoryPage.tsx
src/components/pages/SearchResultPage/SearchResultPage.tsx
src/components/pages/StoreDetailPage/ReviewInputBottomSheet/ReviewInputBottomSheet.tsx
src/components/pages/StoreDetailPage/StoreDetailPage.style.tsx
src/components/pages/StoreDetailPage/StoreDetailPage.tsx
src/components/pages/StoreDetailPage/StoreReviewItem/StoreReviewItem.style.tsx
src/components/pages/StoreDetailPage/StoreReviewItem/StoreReviewItem.tsx
src/constants/api.tsx
src/stories/ErrorImage.stories.jsx
src/stories/Spinner.stories.jsx

#94 에러, 로딩 관련 처리
- 로딩 스피너, 이미지, 에러이미지 컴포넌트 구현 및 적용
- retry count, size 상수 분리
- sorting하는 chip 로직 수정
- 처음 App 렌더링시 campus 확인 로직 수정

Issue94 에러, 로딩 관련 처리

---

src/api/sendLoginRequest.tsx
src/components/pages/Login/Login.tsx

응답값에서 accessToken으로 접근하지 않고, accessCode로 접근해서 로그인이 되지 않았던 것이였음 
이에 accessToken으로 네이밍 변경 
+ 로그인 되었는지 확인하는 로직을 sessionStorage에 직접 접근하여 확인하는 것으로 고침 
(*일단, 둘 중 무엇때문에 정상작동하는지 몰라서 해당 변경사항 유지하여 pr날림)

Issue102 배포시 로그인이 되지 않았던 문제

---

src/components/common/BottomSheet/BottomSheet.style.tsx
src/components/common/ErrorText/ErrorText.tsx
src/components/common/SearchBar/SearchBar.style.tsx
src/components/common/SearchBar/SearchBar.tsx
src/components/common/Spinner/Spinner.style.tsx
src/components/common/Spinner/Spinner.tsx
src/components/common/StoreListItem/StoreListItem.style.tsx
src/components/layout/Header/Header.style.tsx
src/components/layout/Header/Header.tsx
src/components/layout/MenuDrawer/MenuDrawer.style.tsx
src/components/layout/MenuDrawer/MenuDrawer.tsx
src/components/pages/CampusSelectPage/CampusSelectPage.style.tsx
src/components/pages/CampusSelectPage/CampusSelectPage.tsx
src/components/pages/CategoryDetailPage/CategoryDetailPage.tsx
src/components/pages/CategoryPage/Category/Category.tsx
src/components/pages/CategoryPage/CategoryItem/CategoryItem.style.tsx
src/components/pages/CategoryPage/CategoryItem/CategoryItem.tsx
src/components/pages/Login/Login.tsx
src/components/pages/SearchResultPage/SearchResultPage.style.tsx
src/components/pages/SearchResultPage/SearchResultPage.tsx
src/components/pages/StoreDetailPage/ReviewInputBottomSheet/ReviewInputBottomSheet.style.tsx
src/components/pages/StoreDetailPage/ReviewInputBottomSheet/ReviewInputBottomSheet.tsx
src/components/pages/StoreDetailPage/StoreDetailPage.style.tsx
src/components/pages/StoreDetailPage/StoreDetailPage.tsx
src/components/pages/StoreDetailPage/StoreDetailTitle/StoreDetailTitle.tsx
src/components/pages/StoreDetailPage/StoreReviewItem/StoreReviewItem.style.tsx
src/constants/api.tsx
src/constants/messages.tsx
src/context/CampusContextProvider.tsx
src/style/GlobalStyle.tsx

#104 
코드 볼수록 처리 안된게 뭐가 많아서 일단 보이는대로 다 수정해봤습니다. 그냥 머지하지 말고 커밋 기록이랑 파일 체인지 읽어주세요

Issue104 스타일 수정, 에러 수정, 리팩토링

---

src/App.tsx
src/components/layout/Header/Header.style.tsx
src/components/pages/StoreDetailPage/ReviewInputBottomSheet/ReviewInputBottomSheet.tsx
src/constants/messages.tsx
src/constants/rules.tsx

입력 값 예외처리: 메뉴 - 20자, content - 255자
토큰 만료 시나리오: alert 후 로그아웃 처리
추가적으로 route 순회할 때 key prop 없어서 발생하던 오류 수정, 로고 옆 캠퍼스가 방문 후 색상 변경되는 현상 수정

Issue106 예외처리 추가 및 오류 수정

---

public/index.html

Issue109 구글 애널리틱스 태그 추가

---

src/components/common/SearchBar/SearchBar.style.tsx
src/components/common/SearchBar/SearchBar.tsx
src/components/layout/Header/Header.style.tsx
src/components/layout/Header/Header.tsx

상단 내브바에서 검색창 오픈 시 레이아웃이 무너짐
검색창을 하단으로 내려서 항상 떠있는 방향으로 수정
페이지 이동 시에는 검색창이 비워짐
closed #111

Issue111 상단 내브바 검색창 오류 수정

---

.github/workflows/sonar-cloud-analysis-build.yml
package.json
sonar-project.js
sonar-project.properties

sonar cloud에서 제공하는 github action app을 사용하는 것이 아닌 실제 빌드를 돌려서 사용하여 리포트를 전달하도록 수정

fix: sonar analysis 동작 구조 수정

---

src/api/fetchReviewList.tsx
src/api/sendStoreDemandDeleteRequest.tsx
src/api/sendStoreDemandPostRequest.tsx
src/api/sendStoreDemandPutRequest.tsx
src/components/layout/Header/Header.tsx
src/components/layout/MenuDrawer/MenuDrawer.tsx
src/components/pages/StoreDemandPage/StoreDemandPage.tsx
src/components/pages/StoreDetailPage/ReviewUpdateBottomSheet/ReviewUpdateBottomSheet.tsx
src/components/pages/StoreDetailPage/StoreDetailPage.tsx
src/constants/api.tsx
src/mock/handlers/reviewHandler.ts
src/style/GlobalStyle.tsx

- 리뷰 작성 시 별점 입력 오류
- 메뉴 서랍 오류
- global style에 글자 기본색 검정색 반영
등

[Hotfix] 배포 후 발생한 핫픽스를 소스 코드에 반영

---

.github/workflows/build-deploy.yml

배포 자동화 기능 추가

---

src/components/pages/CategoryPage/CategoryPage.tsx
src/components/pages/CategoryPage/RandomPick/RandomPick.style.tsx
src/components/pages/CategoryPage/RandomPick/RandomPick.tsx

홈 화면에 랜덤 식당 룰렛 구현
기존의 랜덤 API를 재활용하고 UI 위주로 구현

랜덤 식당 룰렛 구현

---

src/components/common/StoreListItem/StoreListItem.style.tsx
src/components/common/StoreListItem/StoreListItem.tsx

아래와 같이 별점에 대한 한층 더 상세한 정보를 볼 수 있도록 수정

식당 목록에서 별점을 숫자로 표기하도록 변경

---

src/constants/api.tsx
src/hooks/useRandomPick.tsx
src/util/randomUtils.ts

- crypto.getRandomNumber로 변경
- 후보 숫자 10개로 증가
- 룰렛 판 개수 10번 반복으로 감소

feat: random 로직 개선

---

public/404.html
public/index.html

아래 해결책 참고
https://create-react-app.dev/docs/deployment/#notes-on-client-side-routing
https://github.com/rafgraph/spa-github-pages

hotfix: 404 페이지 작동 오류 수정

---

src/components/common/Star/Star.style.tsx
src/components/common/Star/Star.tsx
src/components/common/StarRating/StarRating.tsx
src/components/common/StoreListItem/StoreListItem.tsx
src/components/pages/StoreDetailPage/StoreDetailPage.style.tsx
src/components/pages/StoreDetailPage/StoreDetailTitle/StoreDetailTitle.style.tsx
src/components/pages/StoreDetailPage/StoreDetailTitle/StoreDetailTitle.tsx
src/components/pages/StoreDetailPage/StoreReviewItem/StoreReviewItem.style.tsx
src/components/pages/StoreDetailPage/StoreReviewItem/StoreReviewItem.tsx
src/index.tsx
src/mock/data.ts
src/types/ui.ts

#158 
검색창 부분은 router 설정도 같이 건드려야해서 이번 브랜치에서는 다루지 않았습니다.

Issue158 가게 상세페이지 디자인 수정
